baseURL = 'https://ehan.pl/'
languageCode = 'pl-pl'
defaultContentLanguage = 'pl'
title = 'EHAN'
theme = 'hugo-universal-theme'

pluralizelisttitles = false

[params]
default_sharing_image = "img/sharing-default.png"
copyright = "Copyright © 2024 PW EHAN. <a href='https://github.com/pwehan/pwehan.github.io/blob/main/LICENSE' target='_blank'>MIT License</a>."

style = 'green'
facebook_site = "pwehan"

enableGoogleMaps = true
googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY" # https://github.com/devcows/hugo-universal-theme/blob/b34533c67125ed52e39b21be89871329a4d08141/exampleSite/config.toml#L403
latitude = "53.243655"
longitude = "22.929595"

disabled_logo = false
logo_text = "EHAN"
logo = "img/logo.jpg"
logo_small = "img/logo-small.png"

address = """<p class="text-uppercase"><strong>PW EHAN Andrzej Niedźwiedź</strong>
<br>Mickiewicza 30
<br>Narewka 17-220
<br>
<strong>Poland</strong>
<br>"""

[params.widgets]
categories = true
tags = true
search = true

[permalinks]
blog = "/blog/:year/:month/:day/:filename/"

[languages]

[languages.pl]
languageName = "Polski"
contentDir = 'content/pl'

[languages.en]
languageName = "English"
contentDir = 'content/en'

[languages.pl.params]
defaultKeywords = ["ehan", "pw ehan", "andrzej niedźwiedź", "avant", "miniładowarki"]
defaultDescription = "Przedsiębiorstwo Wielobranżowe EHAN"

about_us = """<p>
Ładowarki Avant – sprzedaż, serwis, osprzęt i doradztwo.
Wysłuchamy, doradzimy w dopasowaniu do Twoich potrzeb miło, sympatycznie, rzeczowo!
</p>"""

contact_url = "/contact"

[languages.pl.params.topbar]
enable = true
text = """<p class="hidden-sm hidden-xs">Skontaktuj się poprzez +48 512 029 889 lub kontakt@ehan.pl.</p>
  <p class="hidden-md hidden-lg"><a href="tel:+48 512 029 889" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
  <a href="mailto:kontakt@ehan.pl" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
  </p>"""

[languages.en.params]
defaultKeywords = ["ehan", "pw ehan", "andrzej niedźwiedź", "avant", "miniloaders"]
defaultDescription = "EHAN, MNC."

about_us = """<p>
Avant Miniloaders – sales, service, equipment and consulting.
We will listen and advise you in a way that suits your needs in a nice, friendly and objective manner!
</p>"""

contact_url = "/en/contact"

[languages.en.params.topbar]
enable = true
text = """<p class="hidden-sm hidden-xs">Contact us through +48 512 029 889 or kontakt@ehan.pl.</p>
  <p class="hidden-md hidden-lg"><a href="tel:+48 512 029 889" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
  <a href="mailto:kontakt@ehan.pl" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
  </p>"""

[languages.pl.menu]

[[languages.pl.menu.main]]
name = "STRONA GŁÓWNA"
identifier = "menu.home"
url = "/"
weight = 1

[[languages.pl.menu.main]]
name = "Kontakt"
identifier = "menu.contact"
url  = "/contact"
weight = 2

[[languages.pl.menu.main]]
name = "Oferta"
identifier = "menu.products"
url = "/products"
weight = 3

[[languages.pl.menu.main]]
name = "Miniładowarki"
url = "/miniloaders"
parent = "menu.products"

[[languages.pl.menu.topbar]]
weight = 1
name = "Phone"
url = "tel:+48 512 029 887"
pre = "<i class='fas fa-2x fa-phone'></i>"

[[languages.pl.menu.topbar]]
weight = 2
name = "Email"
url = "mailto:kontakt@ehan.pl"
pre = "<i class='fas fa-2x fa-envelope'></i>"

[[languages.pl.menu.topbar]]
weight = 3
name = "Facebook"
url = "http://facebook.com/pwehan"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[languages.en.menu]

[[languages.en.menu.main]]
name = "HOME"
identifier = "menu.home"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "Contact"
identifier = "menu.contact"
url  = "/en/contact"
weight = 2

[[languages.en.menu.main]]
name = "Products"
identifier = "menu.products"
url = "/en/products"
weight = 3

[[languages.en.menu.main]]
name = "Miniloaders"
url = "/en/miniloaders"
parent = "menu.products"

[[languages.en.menu.topbar]]
weight = 1
name = "Phone"
url = "tel:+48 512 029 887"
pre = "<i class='fas fa-2x fa-phone'></i>"

[[languages.en.menu.topbar]]
weight = 2
name = "Email"
url = "mailto:kontakt@ehan.pl"
pre = "<i class='fas fa-2x fa-envelope'></i>"

[[languages.en.menu.topbar]]
weight = 3
name = "Facebook"
url = "http://facebook.com/pwehan"
pre = "<i class='fab fa-2x fa-facebook'></i>"

[params.carouselHomepage]
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.features]
enable = true
cols = 2

[languages.pl.params.see_more]
enable = true
icon = "far fa-envelope"
title = "Dowiedz się więcej"
subtitle = "Chętnie odpowiemy na Twoje pytania i pomożemy w każdej sprawie."
link_url = "/contact"
link_text = "Kontakt"

[languages.en.params.see_more]
enable = true
icon = "far fa-envelope"
title = "Learn more"
subtitle = "We will be happy to answer your questions and help you with any matter."
link_url = "/en/contact"
link_text = "Contact"